version: '3'
services:
  app:
    build: docker/php
    container_name: tasks_app
    volumes:
      - ./:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:1.21
    container_name: tasks_nginx
    ports:
      - 03072:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/tasks-project.conf:/etc/nginx/conf.d/tasks-project.conf
    depends_on:
      - app
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    ports:
      - 3303:3303
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: tasks_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 030721:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=myadmin